### ISSUE TITLE
Repository as template?

### ISSUE THREAD

**Issue by dhruvsaxena1998** [ixartz/Serverless-Boilerplate-Express-TypeScript#5]
Hey, love your work for the boilerplate. Wouldn't it be great if you enable the `Template repository` checkbox under repository settings. It would resolve all the hassle of cloning your repo and doing other changes. Just a suggestion.

![image](https://user-images.githubusercontent.com/14231264/151663660-06726bc4-aa58-4f8c-ae54-c84f99e3b279.png)

**Comment by ixartz** [comment]
Hi @dhruvsaxena1998, thank you for your message and your suggestion.
I have tried the feature at the beginning when GitHub has released this feature. Maybe they improve this feature since then. But, my first experience wasn't good.

With fork you can still track how the origin has evolved and you can easily see the difference since your last pull.
With "template", you lost the history and it's not really easy to update from the origin. You cannot easily know how the origin has evolved and you cannot update your code easily to the latest version.

That is just a personal preference and don't know how useful is this feature to other developers.
